Eval_input_text_LLM:
  preset_text:
    system:
      role: "system"
      content:
        '''
        다음 두 텍스트를 비교하여, 생성된 음악 묘사가 소설 텍스트의 감정, 분위기, 등장인물의 심리(예: 복수심, 긴장감 등) 및 스토리 전개와 관련된 주요 정보를 얼마나 잘 반영하고 있는지 정량적으로 평가해 주세요. 각 평가 항목에 대해 0에서 10까지의 점수와 그 이유를 간략하게 설명해 주세요.

        [평가 항목]
        1. 감정 반영도:
        - 소설 텍스트에 나타난 감정(예: 고통, 복수심, 긴장 등)이 음악 묘사에 얼마나 잘 반영되어 있는지 평가합니다.
        - 0점: 전혀 반영되지 않음 / 10점: 완벽하게 반영됨

        2. 분위기 일치도:
        - 소설 텍스트가 전달하는 전반적인 분위기(어둡고 무거운, 스릴 넘치는 등)가 음악 묘사에 얼마나 일관되게 나타나는지 평가합니다.
        - 0점: 전혀 다른 분위기 / 10점: 매우 일치함

        3. 등장인물 감정 표현 반영도:
        - 소설 속 등장인물의 내면 감정이나 심리가 음악적 요소(멜로디, 리듬, 악기 선택 등)에 얼마나 효과적으로 표현되어 있는지 평가합니다.
        - 0점: 등장인물 감정이 전혀 드러나지 않음 / 10점: 등장인물 감정이 완벽하게 반영됨

        4. 정보 및 스토리 일관성:
        - 소설에서 제시된 스토리의 중요한 정보(예: 복수, 갈등, 긴장감 등)가 음악 묘사에서 왜곡 없이 일관되게 전달되고 있는지 평가합니다.
        - 0점: 주요 정보가 왜곡되거나 누락됨 / 10점: 모든 정보가 정확하게 반영됨

        5. 종합 평가:
        - 위의 항목들을 종합하여, 생성된 음악 묘사가 소설 텍스트의 핵심 감정, 분위기, 등장인물 심리 및 스토리 전개를 얼마나 잘 반영하는지 평가합니다.
        - 0점: 전반적으로 부적절함 / 10점: 전반적으로 완벽하게 일치함

        [예시]
        소설 텍스트:
        "주인공은 어둠 속에서 복수심에 불타며, 과거의 상처와 아픔을 안고 범죄 세계에 뛰어들었다. 그의 눈빛은 차갑고, 마음속 깊은 곳에서는 잊지 못할 고통이 번져나갔다."

        생성된 음악 묘사:
        • 멜로디:  
          현악기와 타악기의 조합으로 긴장감을 고조시키는 어두운 분위기의 멜로디.
        • 장르와 분위기:  
          범죄, 스릴러 장르로, 주인공의 복수와 긴장감을 표현하는 무거운 분위기를 전달.
        • 악기 구성:  
          첼로, 바이올린, 드럼, 베이스를 주요 악기로 사용하여 어둡고 긴장감 넘치는 사운드스케이프를 구현.
        • 템포와 리듬:  
          주인공의 복잡한 감정을 표현하기 위해 느리고 불규칙한 리듬과 긴장감을 고조시키는 템포를 사용.
        • 음악적 요소:  
          불협화음과 격정적인 멜로디를 활용하여 주인공의 복수심과 긴장감을 더욱 강조하며, 강렬한 비트를 통해 스토리의 전개를 더욱 생생하게 전달.

        위 예시를 참고하여, 각 항목별로 0~10 점수와 그 이유를 간략히 설명해 주세요.
        '''
    user:
      role: "user"

  request_params:
    messages: preset_text
    topP: 0.7
    topK: 1
    maxTokens: 300
    temperature: 0.5
    repeatPenalty: 1.5
    stopBefore: []
    includeAiFilters: True
    seed: 0