Input_text_gen_LLM:
  preset_text: 
    system:
      role: "system"
      content_KR: 
        '''
        이 내용에서 시간, 장소, 사건, 그리고 감정적 분위기의 흐름을 파악한 뒤, MusicGen 모델에 전달할 텍스트를 생성하세요. 프롬프트의 구조는 다음과 같습니다:\n
        • 멜로디\n
        • 장르와 분위기\n
        • 악기 구성\n
        • 템포와 리듬\n
        • 음악적 요소\n
        소설 텍스트 데이터를 한줄 한줄 잘 읽어보면서, 소설의 분위기나 감정이 어떤식으로 흘러가는지 잘 파악해서 텍스트를 생성해주세요.
        \n다음은 예시입니다.\n
        • 멜로디:\n전자음이 특징인 경쾌하고 미래적인 멜로디.
        • 장르와 분위기:\n전자 댄스 음악(EDM) 장르로, 에너지 넘치고 낙관적인 분위기를 전달.
        • 악기 구성:\n신디사이저, 드럼, 베이스를 주 악기로 사용하여 현대적이고 생동감 있는 사운드스케이프를 구현.
        • 템포와 리듬:\n빠르고 역동적인 리듬과 함께 박진감 넘치는 템포로 춤추기 좋은 에너지를 제공.
        • 음악적 요소:\n중독성 있는 훅(hook), 역동적인 드롭(drop), 그리고 강렬한 비트를 포함해 곡을 기억에 남고 매력적으로 만듦.
        \n가사없는 노래를 생성할 것이므로, 가사에 대해서는 고려하지 않습니다.
        '''
      content_US: 
        '''
        Please analyze the flow of time, place, events, and emotional atmosphere from the given novel text.\n
        Based on this analysis, generate a text prompt to be fed into the MusicGen model.\n
        The structure of the prompt should be as follows:\n
        •	Melody\n
        •	Genre and Mood\n
        •	Instrumentation\n
        •	Tempo and Rhythm\n
        •	Musical Elements\n
        Carefully read each line of the novel text to grasp the flow of emotions and the atmosphere. Create a prompt that accurately reflects these elements.

        \nHere’s an example:\n
        • Melody:\n
        An upbeat, futuristic melody characterized by electronic sounds.\n
        •	Genre and Mood:\n
        Electronic Dance Music (EDM) genre with a high-energy and optimistic vibe.\n
        •	Instrumentation:\n
        Synthesizers, drums, and bass as the primary instruments, creating a modern and vibrant soundscape.\n
        •	Tempo and Rhythm:\n
        A fast and dynamic rhythm with a driving tempo, delivering danceable energy.\n
        •	Musical Elements:\n
        Includes catchy hooks, dynamic drops, and a strong beat, making the track memorable and engaging.\n

        \nSince this will be an instrumental piece, there is no need to consider lyrics.

        The following items are rules that must be strictly followed when generating text!
        - When generating sentences, always use English only.
        '''
    user: 
      role: "user"

  request_params:  
    messages: preset_text
    topP: 0.7
    topK: 1
    maxTokens: 300
    temperature: 0.5
    repeatPenalty: 1.5
    stopBefore: []
    includeAiFilters: True
    seed: 0
  
Origin_fiction_dir:
  "../novel_content_450000_중간과정.csv"

New_fiction_dir:
  "../new_fic_US.csv"
